// Hero carousel — slides are discovered at runtime by listing the
// images/slides/ folder through the GitHub contents API (GitHub Pages
// itself can't list directories). Drop any image into that folder and
// push: it becomes a slide, ordered by filename.
(function () {
  var REPO = 'dajaca25/SpacerciseWeb';
  var SLIDES_DIR = 'images/slides';
  var SLIDE_SECONDS = 5;
  var IMAGE_RE = /\.(jpe?g|png|webp|gif|avif)$/i;

  var track = document.getElementById('track');
  var dotsWrap = document.getElementById('dots');

  // Prefer the GitHub API (always current); fall back to the slides.json
  // manifest served from this site (regenerated by a GitHub Action whenever
  // the folder changes) when the API is rate-limited or unreachable.
  fetch('https://api.github.com/repos/' + REPO + '/contents/' + SLIDES_DIR)
    .then(function (res) {
      if (!res.ok) throw new Error('api unavailable');
      return res.json();
    })
    .then(function (entries) {
      return (Array.isArray(entries) ? entries : [])
        .filter(function (e) { return e.type === 'file'; })
        .map(function (e) { return e.name; });
    })
    .catch(function () {
      return fetch('slides.json', { cache: 'no-cache' })
        .then(function (res) { return res.ok ? res.json() : []; });
    })
    .then(function (names) {
      var files = (Array.isArray(names) ? names : [])
        .filter(function (name) { return IMAGE_RE.test(name); })
        .sort(function (a, b) { return a.localeCompare(b, undefined, { numeric: true }); });
      if (files.length) start(files);
      // else: keep the placeholder slide that's already in the HTML
    })
    .catch(function () { /* nothing reachable — placeholder stays */ });

  function start(files) {
    track.innerHTML = '';
    dotsWrap.innerHTML = '';
    var dots = [];
    var idx = 0;

    files.forEach(function (name, i) {
      var slide = document.createElement('div');
      slide.className = 'slide';
      var img = document.createElement('img');
      img.src = SLIDES_DIR + '/' + name;
      img.alt = 'Spacercise gameplay screenshot ' + (i + 1);
      slide.appendChild(img);
      track.appendChild(slide);

      var dot = document.createElement('button');
      dot.setAttribute('aria-label', 'Go to screenshot ' + (i + 1));
      dot.addEventListener('click', function () { idx = i; render(); });
      dotsWrap.appendChild(dot);
      dots.push(dot);
    });

    function render() {
      track.style.transform = 'translateX(-' + idx * 100 + '%)';
      dots.forEach(function (dot, i) {
        dot.classList.toggle('active', i === idx);
      });
    }
    render();

    if (files.length > 1) {
      setInterval(function () {
        idx = (idx + 1) % files.length;
        render();
      }, SLIDE_SECONDS * 1000);
    }
  }
})();

// Email signup — front-end confirmation only (GitHub Pages is static; see README
// for hooking up a real mailing-list service).
(function () {
  var form = document.getElementById('signup-form');
  var btn = document.getElementById('signup-btn');
  form.addEventListener('submit', function (e) {
    e.preventDefault();
    btn.textContent = 'Signed up ✓';
  });
})();
